version: "3"

services:
  app:
    build: .
    links:
      - db
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    volumes:
      - ./:/app
    command: >
      sh -c "./manage.py runserver 0.0.0.0:8000"