# Generated by Django 3.0.2 on 2020-01-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('installd', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(through='main.DependencyRelation', to='main.Package')),
            ],
        ),
        migrations.AddField(
            model_name='dependencyrelation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.Package'),
        ),
        migrations.AddField(
            model_name='dependencyrelation',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main.Package'),
        ),
        migrations.CreateModel(
            name='AlternativesDependencyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', models.ManyToManyField(to='main.Package')),
                ('source_packages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_packages', to='main.Package')),
            ],
        ),
    ]
