# Generated by Django 3.0.2 on 2020-01-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_package_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativesdependencyes',
            name='source_packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_packages', to='main.Package'),
        ),
        migrations.AlterField(
            model_name='dependencyrelation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='main.Package'),
        ),
        migrations.AlterField(
            model_name='dependencyrelation',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target', to='main.Package'),
        ),
    ]
